---
# tasks file for mysql
#
  - name: Install MySQL community repository
    yum:
      name: "http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm"
      state: present

  - name: Install MySQL database
    yum:
      name: "mysql-community-server.x86_64"
      state: present
      name: "mysql-community-devel.x86_64"
      state: present

  - name: create MySQL configuration file
    copy:
      content: |
        [client]
        user=root
        password="@targ8et"
      dest: "/etc/.my.cnf"

  - name: Start SQL service
    service:
      name: "mysqld"
      state: started
      enabled: yes

  - name: Create Application Database
    mysql_db:
      name: employee_db
      state: present

  - name: Create Database user
    mysql_user:
      name: db_user
      password: Passw0rd
      priv: '*.*:ALL'
      state: present

